###
GET http://localhost:8080/api/v1/Students

###
POST http://localhost:8080/api/v1/Students
Content-Type: application/json

{
  "name": "Ricky",
  "book": "Computer Science"
}

###
POST http://localhost:8080/api/v1/Students
Content-Type: application/json

{
"name": "Kenny",
"book": "Computer"
}